spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/proiectAndroid
spring.datasource.username=root
spring.datasource.password=adrian2005


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


SECRET_KEY=5e0a36c198ea02ad460d3e82faca99e740f87e9c9575442572d6b7cddc5d19ec
