spring.application.name=backend

spring.datasource.url=jdbc:postgresql://dpg-d6quhli4d50c73bk8ts0-a/proiectandroid
spring.datasource.username=proiectandroid_user
spring.datasource.password=LOm1BCYteoHGqIJkk1vBuwWBLaWJ5WKu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

SECRET_KEY=5e0a36c198ea02ad460d3e82faca99e740f87e9c9575442572d6b7cddc5d19ec

server.port=${PORT:8080}